"use client";

import { useEffect, useState } from "react";

import { ApiErrorAlert } from "@/components/feedback/api-error-alert";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import { Skeleton } from "@/components/ui/skeleton";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";
import { listPositionCommissionRewards } from "@/features/position-history/api";
import type {
  GlobalPosition,
  PositionCommissionReward,
} from "@/features/position-history/types";
import { formatBrokerApiError } from "@/lib/api/errors";

type PositionCommissionRewardsDialogProps = {
  position: GlobalPosition | null;
  open: boolean;
  onOpenChange: (open: boolean) => void;
};

function formatAmount(reward: PositionCommissionReward): string {
  if (!reward.amount) {
    return "—";
  }

  return `${reward.amount.major_units} ${reward.amount.currency.code}`;
}

export function PositionCommissionRewardsDialog({
  position,
  open,
  onOpenChange,
}: PositionCommissionRewardsDialogProps) {
  const [rewards, setRewards] = useState<PositionCommissionReward[]>([]);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    if (!open || !position) {
      return;
    }

    const accountId = position.trading_account.id;
    const positionId = position.id;
    let cancelled = false;

    async function loadRewards() {
      setLoading(true);
      setError(null);

      try {
        const response = await listPositionCommissionRewards(accountId, positionId);
        if (!cancelled) {
          setRewards(response.data);
        }
      } catch (loadError) {
        if (!cancelled) {
          setRewards([]);
          setError(formatBrokerApiError(loadError));
        }
      } finally {
        if (!cancelled) {
          setLoading(false);
        }
      }
    }

    void loadRewards();

    return () => {
      cancelled = true;
    };
  }, [open, position]);

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="flex max-h-[90vh] min-w-0 flex-col gap-0 overflow-hidden sm:max-w-2xl">
        <DialogHeader className="shrink-0">
          <DialogTitle>IB commission rewards</DialogTitle>
          <DialogDescription>
            Rewards generated by position {position?.order_id ?? position?.id ?? ""}.
          </DialogDescription>
        </DialogHeader>

        <div className="min-h-0 flex-1 overflow-auto py-4">
          {loading ? (
            <div className="space-y-2">
              {Array.from({ length: 3 }).map((_, index) => (
                <Skeleton key={index} className="h-10 w-full" />
              ))}
            </div>
          ) : null}

          {error ? <ApiErrorAlert title="Could not load IB commission rewards" message={error} /> : null}

          {!loading && !error && rewards.length === 0 ? (
            <p className="rounded-lg border p-6 text-center text-sm text-muted-foreground">
              No IB commission rewards were found for this position.
            </p>
          ) : null}

          {!loading && !error && rewards.length > 0 ? (
            <Table>
              <TableHeader>
                <TableRow>
                  <TableHead>Level</TableHead>
                  <TableHead>Status</TableHead>
                  <TableHead className="text-right">Rate</TableHead>
                  <TableHead className="text-right">Amount</TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                {rewards.map((reward) => (
                  <TableRow key={reward.reward_id}>
                    <TableCell>{reward.level}</TableCell>
                    <TableCell><Badge variant="secondary">{reward.payment_status}</Badge></TableCell>
                    <TableCell className="text-right">{reward.rate ?? "—"}</TableCell>
                    <TableCell className="text-right">{formatAmount(reward)}</TableCell>
                  </TableRow>
                ))}
              </TableBody>
            </Table>
          ) : null}
        </div>

        <DialogFooter className="shrink-0">
          <Button type="button" variant="outline" onClick={() => onOpenChange(false)}>
            Close
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}
